services:
  tor:
    image: "ssh/tor:${BUILD_VERSION}"
    network_mode: host
    container_name: ${CONTAINER_NAME}
    build:
      context: tor
      dockerfile: Dockerfile
    command: "/restart.sh"
    env_file:
      - ./.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    volumes:
      - data:/var/lib/tor
volumes:
  data: